name: Feature Request
description: Suggest an enhancement to Discordant
title: "[Feature]: "
labels: enhancement
body:
  - type: textarea
    attributes:
      label: Motivation
      description: Describe what problem you're trying to solve.
      placeholder: |
        E.g,. configuration is clumsy because I have to repeat myself a lot.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: |
        Describe your feature request, clearly and consisely. Include any visuals, mockups or other aids that will bring
        clarity to the solution. Don't give a fully-fledged design without developer consultation.
      placeholder: |
        E.g., configurations should allow defining custom variables that can avoid need to repeat certain strings.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible alternatives
      description: |
        A concise description of alternative solutions you've considered (if any) and why you don't prefer them.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional details
      description: Add any other context, screenshots, mockups about the feature request here.
