name: Refactoring
description: Suggest a refactoring to improve the Discordant codebase
title: "[Refactoring]: "
labels: ["refactoring"]
body:
  - type: textarea
    attributes:
      label: Motivation
      description: Describe what problem you're trying to solve.
      placeholder: |
        E.g,. version upgrades are painful because we always take a hard dependency on a specific Minecraft version.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: |
        Describe your desired refactoring, clearly and consisely. Include any context that will bring clarity to the
        solution.
      placeholder: |
        E.g., We should abstract out all aspects of Minecraft that we rely on, so that version integrations can be
        little more than shims.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible alternatives
      description: |
        A concise description of alternative solutions you've considered (if any) and why you don't prefer them.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional details
      description: Add any other context, screenshots, mockups about the refactoring here.
